#!/usr/bin/env python3
"""Card Forge Skill helper.

Turns source material into usable Card Forge Cards.

This helper is intentionally standard-library only. It is a deterministic
first-pass cutter, not a proof of correctness. Generated Cards are usable Cards. Operators may edit, trust, index, or ignore them as they choose.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Iterable

TEXT_EXTENSIONS = {
    ".md", ".txt", ".json", ".jsonl", ".yaml", ".yml", ".toml", ".py", ".js",
    ".ts", ".tsx", ".jsx", ".html", ".css", ".sh", ".bash", ".zsh", ".xml",
    ".csv", ".ini", ".cfg", ".env.example",
}

IGNORE_DIRS = {
    ".git", "node_modules", "__pycache__", ".venv", "venv", "dist", "build",
    ".next", ".cache", "target", ".pytest_cache", ".mypy_cache",
}

CARD_TYPE_PRIORITY = [
    ("receipt", "Receipt Card"),
    ("record", "Receipt Card"),
    ("claim", "Contract Card"),
    ("boundary", "Contract Card"),
    ("permission", "Contract Card"),
    ("approve", "Gate Card"),
    ("human", "Gate Card"),
    ("gate", "Gate Card"),
    ("source", "Check Card"),
    ("inventory", "Check Card"),
    ("dependency", "Check Card"),
    ("check", "Check Card"),
    ("audit", "Check Card"),
    ("inspect", "Check Card"),
    ("validate", "Check Card"),
    ("test", "Check Card"),
    ("verify", "Check Card"),
    ("prompt", "Prompt Card"),
    ("template", "Template Card"),
    ("adapter", "Adapter Card"),
    ("script", "Code Card"),
    ("code", "Code Card"),
    ("run", "Action Card"),
    ("build", "Action Card"),
    ("repair", "Action Card"),
    ("fix", "Action Card"),
]

REQUIRED_FIELDS = [
    "card_id", "name", "type", "status", "input", "move", "output", "done_when",
    "stop_if", "receipt", "permissions", "risk_level", "token_size", "source_origin",
]


@dataclass
class SourceDoc:
    path: Path
    rel_path: str
    text: str


@dataclass
class GeneratedCard:
    card_id: str
    name: str
    type: str
    status: str
    input: str
    move: str
    output: str
    done_when: str
    stop_if: str
    receipt: str
    permissions: list[str]
    risk_level: str
    token_size: str
    source_origin: str
    duplicate_risk: str = "none"
    suggested_action: str = "use"
    index_warning_note: str = "Generated by Card Forge Skill; check before indexing or publishing through MCP."


def fail(message: str) -> None:
    print(f"FAIL: {message}", file=sys.stderr)
    raise SystemExit(1)


def slugify(text: str, limit: int = 48) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "_", text.strip().lower()).strip("_")
    s = re.sub(r"_+", "_", s)
    return (s[:limit].strip("_") or "card")


def stable_digest(text: str, length: int = 8) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:length]


def normalize(text: str) -> str:
    return " ".join(re.sub(r"[^a-zA-Z0-9]+", " ", text.lower()).split())


def is_text_file(path: Path) -> bool:
    if path.name == ".env":
        return False
    if path.suffix.lower() in TEXT_EXTENSIONS:
        return True
    if path.name.lower() in {"readme", "license", "makefile", "dockerfile"}:
        return True
    return False


def iter_source_files(source: Path, max_bytes: int) -> Iterable[SourceDoc]:
    if source.is_file():
        paths = [source]
        root = source.parent
    else:
        root = source
        paths = []
        for path in source.rglob("*"):
            if not path.is_file():
                continue
            if any(part in IGNORE_DIRS for part in path.parts):
                continue
            paths.append(path)

    for path in sorted(paths):
        if not is_text_file(path):
            continue
        try:
            raw = path.read_bytes()[:max_bytes]
            text = raw.decode("utf-8")
        except UnicodeDecodeError:
            continue
        except OSError:
            continue
        rel = path.relative_to(root).as_posix() if path != source else path.name
        if text.strip():
            yield SourceDoc(path=path, rel_path=rel, text=text)


def classify_card_type(title: str, body: str, rel_path: str) -> str:
    title_norm = normalize(title)
    for key, card_type in CARD_TYPE_PRIORITY:
        if key in title_norm:
            return card_type

    haystack = normalize(" ".join([rel_path, body[:500]]))
    for key, card_type in CARD_TYPE_PRIORITY:
        if key in haystack:
            return card_type
    if rel_path.endswith((".py", ".js", ".ts", ".sh")):
        return "Code Card"
    return "Action Card"


def risk_level_for(card_type: str, text: str) -> str:
    norm = normalize(text)
    if any(w in norm for w in ["secret", "token", "password", "credential", "private key", "delete", "payment", "prod"]):
        return "high"
    if card_type in {"Gate Card", "Contract Card", "Code Card"}:
        return "medium"
    return "low"


def token_size_for(text: str) -> str:
    # Fast, conservative approximation. This is not tokenizer-accurate.
    words = len(text.split())
    if words < 120:
        return "small"
    if words < 500:
        return "medium"
    return "large"


def permissions_for(card_type: str) -> list[str]:
    if card_type in {"Check Card", "Contract Card", "Gate Card"}:
        return ["read_only", "write_reports"] if card_type != "Gate Card" else ["read_only", "human_required"]
    if card_type == "Code Card":
        return ["read_only", "write_reports"]
    return ["read_only", "write_reports"]


def headings_from_markdown(text: str) -> list[tuple[str, str]]:
    lines = text.splitlines()
    headings: list[tuple[int, str]] = []
    for i, line in enumerate(lines):
        m = re.match(r"^(#{1,4})\s+(.+?)\s*$", line)
        if m:
            headings.append((i, m.group(2).strip()))
    sections: list[tuple[str, str]] = []
    for idx, (line_no, title) in enumerate(headings):
        next_line = headings[idx + 1][0] if idx + 1 < len(headings) else len(lines)
        body = "\n".join(lines[line_no + 1:next_line]).strip()
        if len(title) >= 3 and len(body) >= 20:
            sections.append((title, body))
    return sections


def infer_output_name(title: str, card_type: str) -> str:
    base = slugify(title, 36)
    if card_type == "Receipt Card":
        return f"{base}_receipt.md"
    if card_type == "Prompt Card":
        return f"{base}_prompt.md"
    if card_type == "Contract Card":
        return f"{base}_claim_boundary.md"
    if card_type == "Gate Card":
        return f"{base}_decision.md"
    if card_type == "Check Card":
        return f"{base}_report.md"
    if card_type == "Code Card":
        return f"{base}_change_plan.md"
    return f"{base}_output.md"


def make_card(title: str, body: str, source_origin: str) -> GeneratedCard:
    card_type = classify_card_type(title, body, source_origin)
    name = title.strip()
    digest = stable_digest(f"{source_origin}\n{name}\n{body[:1000]}")
    type_slug = slugify(card_type.replace(" Card", ""), 16)
    name_slug = slugify(name, 40)
    card_id = f"{type_slug}.{name_slug}.generated_{digest}"
    output = infer_output_name(name, card_type)

    move = build_move(name, body, card_type)
    return GeneratedCard(
        card_id=card_id,
        name=name,
        type=card_type,
        status="generated",
        input=build_input(card_type),
        move=move,
        output=output,
        done_when=build_done_when(card_type, output),
        stop_if=build_stop_if(card_type),
        receipt=build_receipt(card_type, output),
        permissions=permissions_for(card_type),
        risk_level=risk_level_for(card_type, body),
        token_size=token_size_for(body),
        source_origin=source_origin,
    )


def build_input(card_type: str) -> str:
    if card_type == "Check Card":
        return "Source files, notes, prior receipts, or run state relevant to the check."
    if card_type == "Contract Card":
        return "Draft claim, output, README text, sales copy, or readiness statement."
    if card_type == "Gate Card":
        return "A proposed risky action, trust decision, publishing decision, or index update."
    if card_type == "Receipt Card":
        return "Run outputs, warnings, blockers, skipped checks, and next-action notes."
    if card_type == "Prompt Card":
        return "Source context, desired outcome, constraints, and blocked changes."
    if card_type == "Code Card":
        return "Source file, error report, target behavior, and change boundary."
    return "Source material, current run state, and relevant prior receipts."


def build_move(name: str, body: str, card_type: str) -> str:
    summary = " ".join(body.split())[:220]
    if card_type == "Check Card":
        return f"Inspect the source material for {name.lower()} and summarize findings with evidence."
    if card_type == "Contract Card":
        return f"Check {name.lower()} against available evidence and remove or flag unsupported claims."
    if card_type == "Gate Card":
        return f"Pause for operator decision on {name.lower()} and record approval, rejection, or revision."
    if card_type == "Receipt Card":
        return f"Record the outcome of {name.lower()}, including what was checked, skipped, blocked, and recommended next."
    if card_type == "Prompt Card":
        return f"Write a focused prompt for {name.lower()} using source context and explicit scope boundaries."
    if card_type == "Code Card":
        return f"Prepare a bounded code action for {name.lower()} without expanding scope."
    return f"Perform the reusable move described by {name}: {summary}"


def build_done_when(card_type: str, output: str) -> str:
    if card_type == "Gate Card":
        return "The operator decision is recorded as APPROVED, REJECTED, or NEEDS_REVISION."
    return f"`{output}` exists and states findings, warnings, blockers, and next action where applicable."


def build_stop_if(card_type: str) -> str:
    if card_type == "Contract Card":
        return "Stop if an unsupported guarantee, safety claim, compliance claim, or production-readiness claim remains."
    if card_type == "Gate Card":
        return "Stop if operator approval is missing or ambiguous."
    if card_type == "Code Card":
        return "Stop if required source files, tests, or change boundaries are missing."
    return "Stop if required source material is missing or the move would require guessing."


def build_receipt(card_type: str, output: str) -> str:
    if card_type == "Gate Card":
        return "Record the decision, decision-maker, rationale, timestamp if available, and next action."
    return f"Record inputs used, result summary, warnings, skipped checks, and path to `{output}`."


def default_cards_from_file(doc: SourceDoc) -> list[GeneratedCard]:
    cards: list[GeneratedCard] = []
    sections = headings_from_markdown(doc.text)
    for title, body in sections:
        if looks_reusable(title, body):
            cards.append(make_card(title, body, doc.rel_path))

    if not cards:
        title = infer_file_title(doc)
        cards.append(make_card(title, doc.text[:1000], doc.rel_path))

    return cards


def looks_reusable(title: str, body: str) -> bool:
    norm = normalize(" ".join([title, body[:300]]))
    reusable_words = {
        "check", "inspect", "validate", "audit", "record", "receipt", "prompt", "gate",
        "approve", "source", "inventory", "dependency", "claim", "boundary", "test", "review",
        "build", "repair", "fix", "run", "publish", "context", "mcp", "index",
    }
    return any(word in norm for word in reusable_words)


def infer_file_title(doc: SourceDoc) -> str:
    rel = doc.rel_path
    norm = normalize(doc.text[:800] + " " + rel)
    if "claim" in norm or "guarantee" in norm:
        return f"Check Claims in {Path(rel).name}"
    if "receipt" in norm:
        return f"Write Receipt from {Path(rel).name}"
    if "test" in norm or "validate" in norm:
        return f"Validate {Path(rel).name}"
    if rel.endswith((".py", ".js", ".ts", ".sh")):
        return f"Review Code File {Path(rel).name}"
    return f"Review Source File {Path(rel).name}"


def load_registry(path: Path | None) -> list[dict]:
    if not path:
        return []
    if not path.exists():
        fail(f"Registry/index not found: {path}")
    records = []
    for i, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError as exc:
            fail(f"Invalid JSONL in registry/index line {i}: {exc}")
    return records


def apply_duplicate_risk(cards: list[GeneratedCard], registry: list[dict]) -> None:
    ids = {str(r.get("card_id", "")) for r in registry}
    names = {normalize(str(r.get("name", ""))) for r in registry}
    moves = {normalize(str(r.get("move", ""))) for r in registry}

    for card in cards:
        reasons = []
        if card.card_id in ids:
            reasons.append("exact card_id match")
        norm_name = normalize(card.name)
        norm_move = normalize(card.move)
        if norm_name and norm_name in names:
            reasons.append("exact name match")
        elif norm_name and any(norm_name in n or n in norm_name for n in names if n):
            reasons.append("name overlap")
        if norm_move and norm_move in moves:
            reasons.append("same move text")

        if not reasons:
            card.duplicate_risk = "none"
            card.suggested_action = "use"
        elif any(r.startswith("exact") or r == "same move text" for r in reasons):
            card.duplicate_risk = "high"
            card.suggested_action = "use_with_index_warning"
        else:
            card.duplicate_risk = "medium"
            card.suggested_action = "use_with_index_warning"
        if reasons:
            card.index_warning_note = "Possible overlap: " + ", ".join(reasons) + ". Check before indexing or publishing."


def dedupe_generated(cards: list[GeneratedCard]) -> list[GeneratedCard]:
    seen = set()
    out = []
    for card in cards:
        key = normalize(card.name + " " + card.move)
        if key in seen:
            continue
        seen.add(key)
        out.append(card)
    return out


def card_to_markdown(card: GeneratedCard) -> str:
    data = asdict(card)
    front = ["---"]
    for key in REQUIRED_FIELDS:
        value = data[key]
        if isinstance(value, list):
            front.append(f"{key}:")
            for item in value:
                front.append(f"  - {json.dumps(item)}")
        else:
            front.append(f"{key}: {json.dumps(value)}")
    front.append("---")
    return "\n".join(front) + f"\n\n# {card.name}\n\n## Input\n\n{card.input}\n\n## Move\n\n{card.move}\n\n## Output\n\n`{card.output}`\n\n## Done when\n\n{card.done_when}\n\n## Stop if\n\n{card.stop_if}\n\n## Receipt\n\n{card.receipt}\n\n## Index notes\n\n- Usable: {'yes' if card.suggested_action in {'use', 'use_with_index_warning'} else 'check'}\n- Duplicate/index warning: {card.duplicate_risk}\n- Suggested action: {card.suggested_action}\n- Reason: {card.index_warning_note}\n"


def write_outputs(cards: list[GeneratedCard], out_dir: Path, source: Path, registry: Path | None) -> None:
    cards_dir = out_dir / "cards"
    receipts_dir = out_dir / "receipts"
    cards_dir.mkdir(parents=True, exist_ok=True)
    receipts_dir.mkdir(parents=True, exist_ok=True)

    for card in cards:
        (cards_dir / f"{card.card_id}.card.md").write_text(card_to_markdown(card), encoding="utf-8")

    with (out_dir / "card_index_worklist.jsonl").open("w", encoding="utf-8") as f:
        for card in cards:
            f.write(json.dumps(asdict(card), ensure_ascii=False) + "\n")

    write_duplicate_report(cards, out_dir / "duplicate_report.md")
    write_suggested_stacks(cards, out_dir / "suggested_stacks.md")
    write_receipt(cards, source, registry, receipts_dir / "card_making_receipt.md")
    write_manifest(cards, source, registry, out_dir / "run_manifest.json")


def write_duplicate_report(cards: list[GeneratedCard], path: Path) -> None:
    risky = [c for c in cards if c.duplicate_risk != "none"]
    lines = [
        "# Duplicate / Overlap Report",
        "",
        f"Generated Cards checked: {len(cards)}",
        f"Cards with overlap warnings: {len(risky)}",
        "",
        "This report is heuristic. It does not prove uniqueness or correctness.",
        "",
    ]
    if risky:
        for card in risky:
            lines.extend([
                f"## `{card.card_id}` — {card.name}",
                "",
                f"- Duplicate/index warning: `{card.duplicate_risk}`",
                f"- Suggested action: `{card.suggested_action}`",
                f"- Note: {card.index_warning_note}",
                "",
            ])
    else:
        lines.append("No duplicate or overlap warnings found.")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_suggested_stacks(cards: list[GeneratedCard], path: Path) -> None:
    groups: dict[str, list[GeneratedCard]] = {}
    for card in cards:
        groups.setdefault(card.type, []).append(card)
    lines = ["# Suggested Stack Groupings", ""]
    for card_type, group in sorted(groups.items()):
        stack_id = "stack." + slugify(card_type.replace(" Card", "")) + ".generated"
        lines.extend([f"## `{stack_id}`", "", f"Suggested for {card_type}s.", ""])
        for card in group:
            lines.append(f"- `{card.card_id}` — {card.name}")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_receipt(cards: list[GeneratedCard], source: Path, registry: Path | None, path: Path) -> None:
    usable_count = len(cards)
    has_index_warning = [c for c in cards if c.suggested_action != "use"]
    lines = [
        "# Card Forge Receipt",
        "",
        f"Source: `{source}`",
        f"Registry/index used: `{registry}`" if registry else "Registry/index used: none",
        "",
        f"Generated Cards: {len(cards)}",
        f"Usable Cards: {usable_count}",
        f"Cards with index warnings: {len(has_index_warning)}",
        "",
        "## Claim boundary",
        "",
        "Generated Cards are usable Cards, but this run does not guarantee correctness, safety, uniqueness, or production readiness.",
        "Operators decide which Cards to trust, edit, index, publish through MCP, or ignore.",
        "",
        "## Generated Cards",
        "",
    ]
    for card in cards:
        lines.append(f"- `{card.card_id}` — {card.name} ({card.type}, duplicate_risk={card.duplicate_risk}, action={card.suggested_action})")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_manifest(cards: list[GeneratedCard], source: Path, registry: Path | None, path: Path) -> None:
    manifest = {
        "tool": "card_forge_skill.py",
        "source": str(source),
        "registry": str(registry) if registry else None,
        "generated_cards": len(cards),
        "outputs": [
            "cards/",
            "card_index_worklist.jsonl",
            "duplicate_report.md",
            "suggested_stacks.md",
            "receipts/card_making_receipt.md",
        ],
    }
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Turn source material into usable Card Forge Cards.")
    parser.add_argument("--source", required=True, help="Source file or folder to inspect.")
    parser.add_argument("--registry", help="Optional existing Card registry/index JSONL for duplicate warnings.")
    parser.add_argument("--out", default="_card_making_out", help="Output directory.")
    parser.add_argument("--max-cards", type=int, default=24, help="Maximum Cards to emit.")
    parser.add_argument("--max-bytes-per-file", type=int, default=120_000, help="Max bytes to read per file.")
    args = parser.parse_args()

    source = Path(args.source).expanduser().resolve()
    registry_path = Path(args.registry).expanduser().resolve() if args.registry else None
    out_dir = Path(args.out).expanduser().resolve()

    if not source.exists():
        fail(f"Source not found: {source}")

    docs = list(iter_source_files(source, args.max_bytes_per_file))
    if not docs:
        fail("No usable text source files found.")

    cards: list[GeneratedCard] = []
    for doc in docs:
        cards.extend(default_cards_from_file(doc))
        if len(cards) >= args.max_cards:
            break

    cards = dedupe_generated(cards)[: args.max_cards]
    registry = load_registry(registry_path)
    apply_duplicate_risk(cards, registry)
    write_outputs(cards, out_dir, source, registry_path)

    index_warnings = sum(1 for c in cards if c.suggested_action != "use")
    print("PASS: Card Forge Skill completed.")
    print(f"  Source files read:         {len(docs)}")
    print(f"  Generated Cards:           {len(cards)}")
    print(f"  Usable Cards:              {len(cards)}")
    print(f"  Cards with index warnings: {index_warnings}")
    print(f"  Duplicate/index warnings:  {index_warnings}")
    print(f"  Output:                    {out_dir}")


if __name__ == "__main__":
    main()
